### ISSUE TITLE
will there be support for writing to ABF files too?

### ISSUE THREAD

**Issue by sg-s** [swharden/pyABF#1]

**Comment by swharden** [comment]
If our goal is just to _read_ ABFs we can hack our way into accessing their data, throwing away "bytes we don't know what they do". When we desire to _write_ ABF files, we need to know what every byte does and I don't think this level of documentation currently exists.

For writing ABF files, I would suggest interacting directly with ABFFIO.DLL provided as part of the [Axon™ pCLAMP® ABF File Support Pack](http://mdc.custhelp.com/app/answers/detail/a_id/18881/~/axon™-pclamp®-abf-file-support-pack-download-page), since we can be assured the ABFs it produces will be able to be read by their software.

If you find or make your own pure-python code to do this, let me know and I'd be happy to incorporate it into this project or link to your project from mine!

**Comment by sg-s** [comment]
thanks for the feedback! I'm writing a small script to rename channels in ABF files. i got it working for files <v2, will do v2+ files today.

**Comment by swharden** [comment]
PS: While my software doesn't create binary ABF files, I do have a script to create ATF files ClampEx and ClampFit can load. I forgot to mention this earlier. For from-scratch synthesis of ABF files, one could use this script to create an ATF then use ClampFit to save it as an ABF:
