### ISSUE TITLE
Support protocols with user list epoch durations

### ISSUE THREAD

**Issue by haganenoneko** [swharden/pyABF#110]
Hi, I just started using pyABF, but am facing some trouble loading protocols in which some voltage step durations are specified using the "User List" feature in Clampex. 

Here is an example of loading the data, where black dashes delineate individual epochs:
![image](https://user-images.githubusercontent.com/24771353/101295641-b341e780-37d3-11eb-9229-4d39b5bf6875.png)

Clearly, the hyperpolarizing voltage steps, supposedly ~1s long in the protocol, do not match what was actually used in the recording. I was wondering if there was a separate command or potential workaround for dealing with such protocols. Thanks!

The image above was generated as follows:
`
for a in abf_files:
            f, ax = plt.subplots(2,1, figsize=(8,6))
            
            for sweepNumber in a.sweepList[:3]:
                a.setSweep(sweepNumber)
                times = np.array(a.sweepX)[:30000] #convert o ms 
                ax[0].plot(times, a.sweepY[:30000], c='b')
                ax[1].plot(times, a.sweepC[:30000], c='r')

                for i, p1 in enumerate(a.sweepEpochs.p1s):
                    epochLevel = a.sweepEpochs.levels[i]
                    epochType = a.sweepEpochs.types[i]
                    print(f"epoch index {i}: at point {p1} there is a {epochType} to level {epochLevel}")
                    
                    for j in range(2):
                        ax[j].axvline(p1/2000, c='k', ls='--', lw=2, alpha=0.5)
            
            ax[0].set_ylabel("Current")
            ax[1].set_ylabel("Command Voltage")
            ax[1].set_xlabel("Time")
            
            plt.tight_layout()
            plt.show()
            plt.close()
            exit()
`
For reference, below is an image of the "User List" feature in Clampex:
![image](https://user-images.githubusercontent.com/24771353/101295428-8b05b900-37d2-11eb-9dcc-3890a1f097aa.png)

**Comment by swharden** [comment]
Hi @haganenoneko, thank you for reporting this! 

Support for user list _levels_ was added in #105, but support for user list _durations_ are not yet supported.

Can you attach one of your ABFs so I can try adding this feature? Thanks!

**Comment by haganenoneko** [comment]
> Hi @haganenoneko, thank you for reporting this!
> 
> Support for user list _levels_ was added in #105, but support for user list _durations_ are not yet supported.
> 
> Can you attach one of your ABFs so I can try adding this feature? Thanks!


Thanks for the reply! I've attached a .zip file containing the .abf file matching the data shown above. 
[user list durations for pyabf.zip](https://github.com/swharden/pyABF/files/5649716/user.list.durations.for.pyabf.zip)

**Comment by swharden** [comment]
Summarizing #105, you can access values in the user list without having to go through the complicated protocol generation steps:

```python
print(abf.userList)
```

Depending on your goal, this might get you there!

**Comment by haganenoneko** [comment]
> Summarizing #105, you can access values in the user list without having to go through the complicated protocol generation steps:
> 
> ```python
> print(abf.userList)
> ```
> 
> Depending on your goal, this might get you there!

Thanks for the suggestion - abf.userList returns None for me.

**Comment by haganenoneko** [comment]
I have something working, but don't know how to contribute (new to Github). I made the following changes:

1. In abf.py, added parsing of userList when reading ABF1 files [this was very, very, very helpful!](https://swharden.com/pyabf/abf1-file-format.md.html#epoch-waveform-and-pulses-group-9-184-bytes)
2.  In waveform.py, added application of userList if enabled. 

Below is an image produced with the modified scripts, using the same data as my original post:
![image](https://user-images.githubusercontent.com/24771353/101307035-5d813580-37fb-11eb-8e9c-c9efe5f4a829.png)

**Comment by swharden** [comment]
Hey @haganenoneko, thanks again for attaching that ABF. It was helpful!

> abf.userList returns None for me.

For me abf.userList contained epoch durations in the ABF file you attached above

```python
abf = pyabf.ABF("durations.abf")
print(abf.userList)
```

```
[4000.0, 6000.0, 6000.0, 10000.0, 20000.0, 30000.0, 30000.0, 30000.0, 30000.0]
```

Inspecting the header with ClampFit:

![image](https://user-images.githubusercontent.com/4165489/102819106-e02ff600-43a0-11eb-9fc3-9d5695fac5c2.png)

We can tell that these times are added to epoch E. It seems like you were able to make this work by editing waveform.py (the file that generates command waveforms from epoch table data), but I'm not sure yet how to determine from the header alone that these user list values apply to epoch E. I looked through the header using `abf.headerLaunch()` ([user-list-durations.HTML.zip](https://github.com/swharden/pyABF/files/5726558/user-list-durations.abf.zip)) but nothing jumped out to me.

Since this applies to stimulus waveform generation (and not actually recorded data), I probably won't prioritize figuring this out at this time, but if we decide to dive into this topic deeper in the future this is a pretty good start! Thanks again for sharing your ABF file 👍

**Comment by haganenoneko** [comment]
Hi, sorry to re-open this issue after such a long time. My solution for ABF1 files has been working well, but I've recently started recording in a newer version of Clampex, and I can't seem to find which epoch is affected by the provided user list in my ABF2 files. 

I can find the values specified in the user list in the `StringsSection`, and can see that there is a variable in the `ABF` object that contains these values:
```
# attempt to populate the user list
firstBlockStrings = self._stringsSection.strings[0].split(b'\x00')        
self.userList = firstBlockStrings[-2].decode("utf-8").split(",")

try:
  self.userList = [float(x) for x in self.userList if x]
except:
  self.userList = None
```

So, like previously, the only thing we're missing is which epoch these values correspond to. Any input would be greatly appreciated! 

For reference, I've included code for how I added support for ABF1 files. 

For the ABF1 header, I made changes to `abf.py`, `waveform.py`, and `abfHeader.py`.

`abf.py` at `ABF._readHeadersV1()`:
```
#user specified list 
if self._headerV1.nULEnable[0] == 0:
    self.userList = None 
    self.userList_ParamToVary = None 
else:
    self.userList = [int(x) for x in self._headerV1.sULParamValueList.split(",")]
    self.userList_ParamToVary = int(self._headerV1.nULParamToVary[0])
```

`waveform.py`  at `EpochTable._initABF1()`:

```
if abf.userList is None:
    pass 
else:
    ParamToVary = abf.userList_ParamToVary - 21
    if ParamToVary > 9: #duration 
        StepToVary = ParamToVary - 10 
    else: #level
        StepToVary = ParamToVary
    
    #make user list same length as number of epochs 
    m1 = len(abf._headerV1.lEpochInitDuration)
    m2 = len(abf.userList)
    
    if m2 < m1:
        abf.userList.extend( [abf.userList[-1]]*(m1-m2) )
    else:
        abf.userList = abf.userList[:m1]

for i in range(20):
    epoch = Epoch()
    epoch.epochNumber = i % 10
    epoch.epochType = abf._headerV1.nEpochType[i]
    
    epoch.duration = abf._headerV1.lEpochInitDuration[i]
    epoch.durationDelta = abf._headerV1.lEpochDurationInc[i]
    epoch.level = abf._headerV1.fEpochInitLevel[i]
    epoch.levelDelta = abf._headerV1.fEpochLevelInc[i]

    if abf.userList is None:
        pass 
    else:
        if i == StepToVary:
            if ParamToVary < 10:
                epoch.level = abf.userList 
                epoch.levelDelta = 0 
                epoch.duration = abf._headerV1.lEpochInitDuration[i]
                epoch.durationDelta = abf._headerV1.lEpochDurationInc[i]
            else:
                epoch.level = abf._headerV1.fEpochInitLevel[i]
                epoch.levelDelta = abf._headerV1.fEpochLevelInc[i]
                epoch.duration = abf.userList 
                epoch.durationDelta = 0 
            
    epoch.pulsePeriod = 0  # not supported in ABF1
    epoch.pulseWidth = 0  # not supported in ABF1
    epochs.append(epoch)
```

In `abfHeader.py`, I added the following to `HeaderV1.__init__()`:
```
# EXTENDED GROUP 12 - Variable parameter user list (1096 bytes)
self.nULEnable = readStruct(fb, "4h", 3360) #4short 
self.nULParamToVary = readStruct(fb, "4h", 3368) #4short 
self.sULParamValueList = readStruct(fb, "1024s", 3376) 
self.nULRepeat = readStruct(fb, "4h", 4400)
```

**Comment by swharden** [comment]
Hi @haganenoneko, 

## ABF1 User List Support

Thanks for sharing your ABF1 code! I'll take a look at it closely soon and perhaps integrate it into the the main project.

Supplementing your code, these tables about the ABF1 header may be useful:
* https://swharden.com/pyabf/abf1-file-format/#variable-parameter-user-list-group-12-82-bytes
* https://swharden.com/pyabf/abf1-file-format/#extended-variable-parameter-user-list-extended-group-12-1096-bytes

## ABF2 User List Support

> I can't seem to find which epoch is affected by the provided user list in my ABF2 files

This may not be currently supported in pyabf, but I'm happy to look into it! 

Clarifying the issue, full support for user lists includes being able to look-up:
* ✔️ user list _values_
* ❌ user list _parameter_ to vary (epoch level, duration, etc.)
* ❌ user list _epoch_ to vary (A, B, C, etc.)

Currently pyabf only supports the first one.

If you have one or two ABF2 files with user lists in them you want to upload, they may be helpful to develop against.

Collecting notes and hopping projects (here's code from a C# library I'm working on), it looks like these code blocks may be useful:

* https://github.com/swharden/ABFsharp/blob/5b79204068aec7258be6f3c02bd2ca6c125bab5c/dev/ABFFIO/axon32/AxAbfFio32/abfheadr.h#L762-L764

* https://github.com/swharden/ABFsharp/blob/5b79204068aec7258be6f3c02bd2ca6c125bab5c/dev/ABFFIO/axon32/AxAbfFio32/abfheadr.h#L883-L888

* https://github.com/swharden/ABFsharp/blob/5b79204068aec7258be6f3c02bd2ca6c125bab5c/dev/ABFFIO/axon32/AxAbfFio32/abfheadr.h#L144-L162

I might move slowly, but I'll definitely keep chipping away at this problem and eventually close this issue when I figure it out (or decide it's something I can't solve). Thanks again for the suggestion! 🚀

**Comment by swharden** [comment]
Hi @haganenoneko, there's actually been some movement here so I think this will be fixed in the next few days.

Since I wrote last and now I substantially rewrote [AbfSharp](https://github.com/swharden/AbfSharp) and it's surprisingly complete now (more complete than pyABF) and it has extensive tests that use the official ABFFIO.DLL to read ABFs and compare their real header values against those I extract from the binary file data. This way I can know with really high confidence I'm reading the header data correctly. In the process I revealed some small/obscure bugs in pyABF I'll be fixing soon, but that's another topic.

Tonight I figured out how to work with more user list parameters by messing with Clampex 11 and editing ABF files in a hex editor. I'll add this to pyABF soon, but for now you can read user list parameters from ABF2 files like this. It's a shortcut that works if you have only 1 user list:

* Determine where the user list is in the ABF file - its block number is stored as a `UInt16` at byte `172`. Multiply this by `512` (bytes per block) to get the byte position in the file of the user list section.
* Move forward 4 bytes (a.k.a., read two `Int16` values and discard them)
* Read an `Int16` value - this is your "user list parameter" value. It'll be different if you user list controls level, duration, etc. 

There are _so many_ potential parameters that it's hard for me to make a list of all of them. [abfoldnx.h#L112-L217](https://github.com/swharden/AbfSharp/blob/5b79204068aec7258be6f3c02bd2ca6c125bab5c/dev/ABFFIO/axon32/AxAbfFio32/abfoldnx.h#L112-L217) hints at a lot of them but these numbers don't seem to match up perfectly. With a little inspection and practice you can probably figure out the common ones you use for your experiments.

I'll leave this issue open and follow-up when I bake this into the pyABF package 👍 🚀

**Comment by swharden** [comment]
Okay, I think this is in a good spot now. I added improved support for user strings (including supporting ABF1 files) in #114 so now you can do this:

```py
abf = pyabf.ABF("user-list-durations.abf")
print(f"ParamNumber={abf.userListParamToVary}")
print(f"ParamName={abf.userListParamToVaryName}")
print(f"ParamValues={abf.userList}")
```

```
ParamNumber=[35] 
ParamName=['EPOCHINITLEVEL'] 
ParamValues=[4000.0, 6000.0, 6000.0, 10000.0, 20000.0, 30000.0, 30000.0, 30000.0, 30000.0]
```

It's not on pypi yet (so you can't get it with pip yet), but if you download pyabf from this repo it's ready to use. I'll work on #111 and plan to release an updated package on pypi soon

Thanks again for suggesting this improvement!
