### ISSUE TITLE
Fails to load files with more adc channels than dac channels

### ISSUE THREAD

**Issue by pnewstein** [swharden/pyABF#121]
In files where the number of adc channels exceeds the number of dac channels
([Example ABF](https://github.com/pnewstein/pyABF/blob/master/data/abfs/test_0001.abf)),  The abf file fails to load with an index error in ```self.sweepUnitsC = self.dacUnits[channel]``` in ```abf.setSweep```.

The ```abf._readHeadersV2```  method seems to handle cases where there are more dac channels than adc channels by cutting off any excess dac channels:

```python
self.dacNames = [self._stringsSection._indexedStrings[x]
                 for x in self._dacSection.lDACChannelNameIndex[:self.channelCount]]
self.dacUnits = [self._stringsSection._indexedStrings[x]
                 for x in self._dacSection.lDACChannelUnitsIndex[:self.channelCount]]
```
However, the inverse (cutting off excess adc channels) would not work, because I need to access the data in those channels.

I have [a fork](https://github.com/pnewstein/pyABF/) that solves this issue with a few try except statements, so that when setting sweep to channels without dac data, ```sweepUnisC```, ```sweepLabelC```, and ```sweepEpochs``` are all undefined. This fork passes all tests when I add the following logic to test_api.py.
```python
if "sweepUnitsC" in dir(abf):
    assert isinstance(abf.sweepUnitsC, str)
    assert isinstance(abf.sweepLabelC, str)
```

**Comment by swharden** [comment]
Hi @pnewstein, thanks for reporting this and working-out a fix! Your PR #122 is very helpful (thanks for fixing the tests and also adding value tests for your new demo ABF!). I'll refine the PR a bit, merge it, and release an update on pypi shortly 👍 

Oh, thanks for fixing the pypi docs too! I see some C# syntax from [AbfSharp](https://github.com/swharden/AbfSharp) syntax sneaked its way into the pyabf docs by accident

**Comment by pnewstein** [comment]
Great! I was considering an alternative solution of changing the signature of ```setSweep``` to something like
```python
  def setSweep(self,
               sweepNumber: int,
               channel: int = 0,
               absoluteTime: bool = False,
               baseline: List[float] = [None, None],
               dac_channel: Optional[int]=None
):
    if dac_channel is None:
        dac_channel = channel
```
This would be backwards compatible and prevent any errors when calling ```sweepUnisC```, ```sweepLabelC```, and ```sweepEpochs```

**Comment by swharden** [comment]
> alternative solution ... backwards compatible

Because this library is relatively stable now and other projects depend on it, I'm highly incentivized to keep the API as stable as possible. Your suggestion of the optional DAC channel argument in `setSweep` is well received, but it's a bit of a band-aid atop another band-aid resulting from the core problem that the API I made a few years ago (when I knew a lot less about ABF files) is a bit sloppy when it comes to channel variable names and doesn't do a good job segregating ADC channels from DAC channels.

I'm experimenting with a few different solutions here, but an ideal one wouldn't change method signatures. Users who just want these labels can reach into the ABF's `adcNames`, `adcNames`, `dacNames`, and `dacUnits` lists. There's also a problem where ADC and DAC channels may be in different orders, so the ones automatically selected and loaded into `sweepLabel` and `sweepUnits` by `setSweep()` may be wrong anyway 😅

Hopefully I can come up with something simple here. Presently I'm leaning toward just setting the sweep label/units to `None` if the array is smaller than expected 🤔
