### ISSUE TITLE
Incorrect gain due to info["nTelegraphEnable"] in ABF 1.3 files

### ISSUE THREAD

**Issue by samuelgarcia** [swharden/pyABF#14]
Same problem in neo.
I open an issue here for collborating.
https://github.com/NeuralEnsemble/python-neo/issues/544

**Comment by swharden** [comment]
**Reference data:** The ABF (v1.3) header for the file [provided by the OP](https://github.com/NeuralEnsemble/python-neo/issues/544) is here:
https://github.com/swharden/pyABF/blob/master/data/headers/130618-1-12.md
I exported this file as an ATF so I can inspect what the first few values are according to ClampFit.

```
"Time (s)"    "Trace #1 (pA)"
0         -188.33
2e-5      -188.33
4e-5      -189.894
6e-5      -191.146
8e-5      -191.771
1e-4      -192.084
1.2e-4    -193.648
1.4e-4    -194.274
1.6e-4    -193.961
1.8e-4    -193.961
2e-4      -194.9
2.2e-4    -195.213
2.4e-4    -194.587
2.6e-4    -194.587
```

**Specific issue:** pyABF calculates the first data point value as `-19.7263` while ClampFit shows it's `-188.33`. Which numbers are correct?

**Telegraph thoughts:** In ABF1 headers, `nTelegraphEnable` is an array of values (one per ADC channel). The values should be 0 (disabled) or 1 (enabled). Any other value other than 0 or 1 is unexpected, and would likely occur only due to file corruption or buggy _de-novo_ synthesis of an ABF file. Since the OP said they created the ABF file using the [SynaptoSoft ABF Utility](http://www.synaptosoft.com/MiniAnalysis/ABFUtility.html), the latter seems most likely. However, my pyABF code ignores `nTelegraphEnable` completely, so while it _is_ buggy it may not be the reason the data is being scaled oddly...

**Comment by swharden** [comment]
After some more research, I figured out what's going on:

### Problem
* The ABF1 file header created by the [SynaptoSoft ABF Utility](http://www.synaptosoft.com/MiniAnalysis/ABFUtility.html) is invalid
* `nTelegraphEnable ` should only have 0s and 1s, but in this file it contains crazy numbers
* This causes data to get scaled by `fTelegraphAdditGain` which contains crazy large numbers

### Solution
If the ABF1 header is crazy, `nTelegraphEnable ` will contain numbers other than 0s and 1s. Therefore, only scale data by `fTelegraphAdditGain` if `nTelegraphEnable==1`, not simply `if nTelegraphEnable`.

A suggested fix for Python-neo was mentioned here:
https://github.com/NeuralEnsemble/python-neo/issues/544
