### ISSUE TITLE
support caching of custom stimulus waveforms

### ISSUE THREAD

**Issue by t-b** [swharden/pyABF#57]
Currently a new instance of ATF is created for every loaded protocol. This takes quite some time and makes it unbearable slow here for ATF files with 20MB.

My old approach of caching the results needs to be resurrected so that this is usable again.

I'll provide a PR.

**Comment by swharden** [comment]
I'd love to help work-out a solution that we both feel good about! 

For reference, this topic was last discussed here: https://github.com/swharden/pyABF/issues/30. At present, the ABF class initialization argument list ([abf.py#L47](https://github.com/swharden/pyABF/blob/master/src/pyabf/abf.py#L47)) is very light. Ideally our solution will seek to preserve this simplicity.

Since pyABF allows loading of custom stimulus waveforms from ABF and ATF files, I'm encouraged to come up with a solution that allows stimulus waveform caching in general. I see that loading the same stimulus file repeatedly is extremely slow, so I'm motivated to find a solution! Would you be willing to share a code example (and perhaps some ABF/ATF data) that shows how you'd like to use cached ATF files? Maybe I can come up with something that supports your application out of the box.

**Comment by swharden** [comment]
I uploaded a code example that shows how to used cached waveforms. In this example a few dozen ABF files are loaded and `abf.sweepC` is assigned a cached stimulus waveform from an ATF file that is only loaded once. This method works for stimulus waveforms in ABF or ATF files. Is this method sufficient to meet your needs?

https://github.com/swharden/pyABF/blob/a397240976a2db866fa8fc65026cfc744972d55a/dev/python/2018-11-17%20stimulus%20caching.py#L19-L39

Output of that script:
```
processing 05210017_vc_abf1 ...
processing 130618-1-12 ...
processing 14o08011_ic_pair ...
processing 14o16001_vc_pair_step ...
processing 16d05007_vc_tags ...
processing 16d22006_kim_gapfree ...
processing 171116sh_0011 ...
processing 171116sh_0012 ...
processing 171116sh_0013 ...
processing 171116sh_0014 ...
processing 171116sh_0015-ATFwaveform ...
processing 171116sh_0015 ...
processing 171116sh_0016 ...
processing 171116sh_0017 ...
processing 171116sh_0018 ...
processing 171116sh_0019 ...
processing 171116sh_0020 ...
processing 171117_HFMixFRET ...
processing 17o05024_vc_steps ...
processing 17o05026_vc_stim ...
processing 17o05027_ic_ramp ...
processing 17o05028_ic_steps ...
processing 180415_aaron_temp ...
processing 18702001-biphasicTrain ...
processing 18702001-cosTrain ...
processing 18702001-pulseTrain ...
processing 18702001-ramp ...
processing 18702001-step ...
processing 18702001-triangleTrain ...
processing 18711001 ...
processing 18713001 ...
processing 18807005 ...
processing 18808025 ...
processing 2018_04_13_0016a_original ...
processing 2018_04_13_0016b_modified ...
processing 2018_08_23_0009 ...
processing 2018_11_16_sh_0006 ...
processing abf1_with_tags ...
processing File_axon_1 ...
processing File_axon_2 ...
processing File_axon_3 ...
processing File_axon_4 ...
processing File_axon_5 ...
processing File_axon_6 ...
processing File_axon_7 ...
processing model_vc_ramp ...
processing model_vc_step ...
processing sine sweep magnitude 20 ...
```

**Comment by t-b** [comment]
@swharden Thanks for looking into that.

My preference would be to have it transparently cached. Meaning the user does not need to worry about it.

My idea was to use a dictionary in `stimulusWaveformfromFile` which caches the ABF/ATF instances and uses the full path as key.

**Comment by swharden** [comment]
@t-b transparent caching would definitely make the higher-level code easier to write! 

I'd be happy with pretty much any method you come up with that doesn't require passing custom objects into the [ABF class initializer](https://github.com/swharden/pyABF/blob/fe38ff40d75dc0e21e778166cedf48a958ac4676/src/pyabf/abf.py#L47) (I try to keep that argument list as simple as possible). I'll be around for the next few days and can incorporate a merge and pypi update pretty quick if you come up with something.

https://github.com/swharden/pyABF/blob/fe38ff40d75dc0e21e778166cedf48a958ac4676/src/pyabf/stimulus.py#L250-L285

**Comment by t-b** [comment]
I've made a PR.

**Comment by swharden** [comment]
Thanks for the fix! It's now live on pypi.
https://github.com/swharden/pyABF/releases/tag/2.0.25

**Comment by swharden** [comment]
**bug identified:**
To date `protocolStorageDir` has been effectively ignored because it was incorrectly referenced as `Stimulus.protocolStorageDir` (which is always empty) rather than `self.protocolStorageDir`. That bug [was here](https://github.com/swharden/pyABF/blob/50bb0ae7c6bfdc9a8f2061a621da42badd7b1ffa/src/pyabf/stimulus.py#L269-L272) will be corrected soon.

**protocolStorageDir will change:**
As I refactor the stimulus module (as part of pyabf 2.1), the fully automatic loading and caching of stimulus files will remain unchanged. However, since apparently no one has ever been able to use `protocolStorageDir` before, I know I won't break anyone's code if I move it out of the Stimulus class (e.g., into an `altPaths` list in the ABF class).

**caching test script:** 
I created a test script to verify stimulus waveform caching functionality (for ATF and ABF waveforms) continues to work as the stimulus module gets refactored: [caching test.py](https://github.com/swharden/pyABF/blob/master/dev/python/2018-12-15%20caching%20test.py)

**Comment by swharden** [comment]
### Change notes
* stimulus waveform loading and caching is still automatic/default/invisible
* alternate stimulus file folder now defined by `abf.stimulusFileFolder`
* caching can be disabled at load with `pyabf.ABF("demo.abf", cacheStimulusFiles=False)`

### Resources
The stimulus module is now small enough to easily review now:
https://github.com/swharden/pyABF/blob/master/src/pyabf/stimulus.py

Tested with:
https://github.com/swharden/pyABF/blob/master/dev/python/2018-12-15%20caching%20test.py

Example ABF using an ATF waveform:
https://github.com/swharden/pyABF/tree/master/data#171116sh_0015-atfwaveformabf
