### ISSUE TITLE
No module named 'pyabf.tools'

### ISSUE THREAD

**Issue by cudmore** [swharden/pyABF#75]
I am very keen on trying out pyabf. First order of business is to detect some action potentials from a whole-cell recording voltage trace. In the examples I see passive membrane properties in 'pyabf.tools.memtest' and looking at the source code, I see basic AP detection in 'pyabf.tools.ap'.

The pyabf.tools is not available in my install? Have I done something wrong or is this a bug/omission?

in python:
   > import pyabf   
   > import pyabf.tools
   ModuleNotFoundError: No module named 'pyabf.tools'

installed with:
   pip3 install --upgrade pyabf
   also tried installing from downloaded /src

my system:
   macOS
   python 3.7.0
   pyabf-2.1.6

**Comment by swharden** [comment]
Hi @cudmore, although pyABF does not _officially_ support event detection at this time (which is why there is no documentation about it), there is a crude tool to get you started ([ap.py](https://github.com/swharden/pyABF/blob/master/src/pyabf/tools/ap.py)). Due to this preliminary nature of event detection, the syntax may change in the future as it gets refined, but for now this works:

I'll start a new issue to remind me to formally implement (and document) event detection for action potentials and spontaneous currents (EPSCs and IPSCs).

### Sample Code

```python
import pyabf
import pyabf.tools.ap
import matplotlib.pyplot as plt

abf = pyabf.ABF("171116sh_0018.abf")

# display AP frequency by sweep
apFirstFreq, apFreqAvg = pyabf.tools.ap.ap_freq_per_sweep(abf)
for sweepNumber, apFreq in enumerate(apFreqAvg):
    print(f"Sweep {sweepNumber} fires at {apFreq} Hz")

# make a plot showing AP detection
abf.setSweep(12)
plt.figure(figsize=(10,4))
plt.plot(abf.sweepX, abf.sweepY)
for apPoint in pyabf.tools.ap.ap_points_currentSweep(abf):
    plt.axvline(abf.sweepX[apPoint], color='r', alpha=.2, ls='--')
plt.tight_layout()
plt.show()
```

### Output (text)
```
Sweep 0 fires at 0 Hz
Sweep 1 fires at 0 Hz
Sweep 2 fires at 0 Hz
Sweep 3 fires at 0 Hz
Sweep 4 fires at 0 Hz
Sweep 5 fires at 0 Hz
Sweep 6 fires at 0.7174887892376681 Hz
Sweep 7 fires at 0.6777363605557438 Hz
Sweep 8 fires at 7.079646017699115 Hz
Sweep 9 fires at 14.760147601476016 Hz
Sweep 10 fires at 28.49002849002849 Hz
Sweep 11 fires at 33.95585738539898 Hz
Sweep 12 fires at 40.98360655737705 Hz
Sweep 13 fires at 45.662100456621005 Hz
Sweep 14 fires at 46.08294930875576 Hz
Sweep 15 fires at 50.89058524173028 Hz
Sweep 16 fires at 59.523809523809526 Hz
```

### Output (image)
![action-potential-event-detection](https://user-images.githubusercontent.com/4165489/52903719-bda28400-31ef-11e9-9a20-f86f446f1be8.png)

**Comment by swharden** [comment]
Event detection implementation will be tracked on https://github.com/swharden/pyABF/issues/76

**Comment by cudmore** [comment]
Thanks for the feedback. I was able to implement what I needed using your excellent examples. My original post was that 'import pyabf.tools' does not work and results in a ModuleNotFoundError. I do not need it any more but do note the import is broken?

```
cudmore@Roberts-iMac:~/Sites/bAnalysis $ python3
Python 3.7.0 (default, Oct  2 2018, 09:19:48) 
[Clang 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyabf
>>> import pyabf.tools.ap
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pyabf.tools'

```
