### ISSUE TITLE
allow installing from git

### ISSUE THREAD

**Issue by swharden** [swharden/pyABF#86]
see why this doesn't work:

```
pip install git+https://github.com/swharden/pyABF.git 
```

**Comment by swharden** [comment]
Actually, installing from git is a bad idea. Just keep pypi up to date and this is unnecessary.

**Comment by cudmore** [comment]
Because your setup.py is in a sub folder named 'src', you need the following

```
pip install "git+https://github.com/cudmore/pyABF#egg=pyabf&subdirectory=src"
```
I am using the double-quotes (") on macOS/Linux, otherwise the '&' is interpreted as a command. Not sure if this one liner works on Windows.

Note, this command installs from my fork in github user @cudmore

See: [pip install](https://pip.pypa.io/en/stable/cli/pip_install/) documentation.
