### ISSUE TITLE
ABF1 file details differ between ABFInfo and pyABF

### ISSUE THREAD

**Issue by t-b** [swharden/pyABF#92]
Looking at the abf1 file from https://github.com/youngseok-seo/NWB/blob/master/data/abf1/19122043.abf I get the following header output from pyabf
[19122043.abf.zip](https://github.com/swharden/pyABF/files/3676716/19122043.abf.zip).

The output from ABFInfo, https://moleculardevices.app.box.com/s/6pazy183dvq7yrxx5l6wx1sdxr4j57wf, is 
[abfinfo-output.txt](https://github.com/swharden/pyABF/files/3676733/abfinfo-output.txt).

Obvious differences:

```
Created: Jan 22, 2019, at 22:22:10.750 [10:56:42]
Created by: Clampex 9.2
Modified by: Clampex 9.2
```

vs
```
abfDateTime = 2019-09-25 16:34:59
```

which just looks like the file creation date.

```
$ ls -l data/abf1/19122043.abf
-rw-r--r-- 1 thomas 197121 6615552 Sep 25 16:34 data/abf1/19122043.abf
```

I can't seem to find the string "ClampEx" in the pyabf HTML file as well.

```
File GUID:       {EA774D20-4346-4219-ACCF-DB3B6DD89ABD}.
```

vs

```
fileGUID = 
```

And now a question :)
Where can I find `nExperimentType = 1` in pyabf?

I need to figure out if I have resources to tackle that on my own.

**Comment by swharden** [comment]
Hi @t-b, thanks for looking into this! I'll look into these topics in more detail within the next few days. For now, here are some quick notes which you may find helpful.

## Date calculation

ABF1 files don't store date information, so the file creation date is "invented" from the file creation time

https://github.com/swharden/pyABF/blob/d91e6bc4e633bd264b043677ef2d0c6f9630183d/src/pyabf/abfHeader.py#L193-L196


ABF2 files have `uFileStartDate` and `uFileStartTimeMS` header variables which are used to create the date like this

https://github.com/swharden/pyABF/blob/d91e6bc4e633bd264b043677ef2d0c6f9630183d/src/pyabf/abfHeader.py#L268-L273

It may be possible that the code in this block is incorrect.

## GUID

ABF1 files don't contain a GUID.

ABF2 file GUIDs are created like this

https://github.com/swharden/pyABF/blob/d91e6bc4e633bd264b043677ef2d0c6f9630183d/src/pyabf/abfHeader.py#L260-L266

It may be possible that the code in this block is incorrect.

## Access `nExperimentType` 

```python
abf = pyabf.ABF("test.abf")
print(abf._protocolSection.nExperimentType)
```

**Comment by swharden** [comment]
Hi @t-b, I somewhat misunderstood this issue in my original response. Most of the suggestions I gave only related to ABF2 files.

I have since added your example ABF1 file to the collection of demo ABFs. Its header values (as assessed by pyABF) can be easily viewed here: [19122043.md](https://github.com/swharden/pyABF/blob/master/data/headers/19122043.md)

My understanding before today was that ABF1 files do not contain acquisition date/time or GUID information. However, you found that the ABFInfo program is able to display these pieces of information from ABF1 files.

## Finding file date in ABF1 files

It looks like file time is a known integer at byte 24:
https://github.com/swharden/pyABF/blob/d91e6bc4e633bd264b043677ef2d0c6f9630183d/src/pyabf/abfHeader.py#L128

I'd bet the date, if there, is a few bytes in either direction.

## Finding the GUID in ABF1 files
The GUID object is 16 bytes. In ABF2 files I think it's located at byte 40. You could try checking out the ABF1 header with a hex editor and modifying bytes until you find the section that corresponds to the GUID. I'd guess it's within the first 100 bytes of the file, if it's there, squeezed between the known header variables:

https://github.com/swharden/pyABF/blob/d91e6bc4e633bd264b043677ef2d0c6f9630183d/src/pyabf/abfHeader.py#L122-L172

## Finding additional header values in ABF1 files

... I'd suggest the same hex editor technique for figuring out where `nExperimentType` is stored in ABF1 files, but this is not easy work! If you find a more comprehensive list of ABF file structure which may help avoid all this work, let me know =]

## The struct map is a hint
The values don't always match the memory layout of structs in [ABFHEADR.H](https://github.com/swharden/vsABF/blob/master/doc/AxonSDK/ABF_FileSupportPack/AxonDev/Comp/ABFFIO/ABFHEADR.H), but they might be close! I'll bet the values you're looking for clump together.

**Comment by t-b** [comment]
@swharden Thanks for the quick response. I'll look into that.

**Comment by swharden** [comment]
ABF1 date time detection works now:

```python
abf = pyabf.ABF(PATH_DATA+"/19122043.abf")
print(f"abfDateTime: {abf.abfDateTime}")
```

```
abfDateTime: 2019-01-22 22:22:10
```

`GUID` and `nExperimentType` remain unsolved...

**Comment by swharden** [comment]
GUID works in ABF1 files now too.

```python
abf = pyabf.ABF(PATH_DATA+"/19122043.abf")
print(f"fileGUID: {abf.fileGUID}")
```

```
fileGUID: {EA774D20-4346-4219-ACCF-DB3B6DD8BDBD}
```

**Comment by swharden** [comment]
poking around in a hex editor I figured out `nExperimentType` is at byte 260 in ABF1 files. This now works:

```python
abf = pyabf.ABF(PATH_DATA+"/19122043.abf")
print(f"nExperimentType: {abf._headerV1.nExperimentType}")
```

```
nExperimentType: 1
```

I think this addresses all of the issues you raised in your original issue. You can see how arduous this process is!

If you think additional variables are useful, let me know and I'll try to implement them. My guess is that the ones in pyABF now are are suitable for most users (and also that most people use ABF2 files these days too).

I'll publish this on pypi this weekend so these new features can be installed with pip

**Comment by t-b** [comment]
@swharden Thanks a lot for handling that so quickly. I've checked the changes and they do fix the issues I had.

**Comment by swharden** [comment]
Note that the GUID calculation has been incorrect by one byte this whole time. This has been fixed, and tests added comparing the GUID to that generated by ABFINFO.exe, but the GUID displayed by pyABF will change by two characters as a result. To make it easier to identify correct vs. incorrect GUIDs produced by pyABF, the Microsoft-style curly braces have been removed. 

This is discussed in #95
